language: objective-c
osx_image: xcode9

xcode_project: LicensesViewController.xcodeproj
xcode_scheme: LicensesViewController

before_install:
  - gem install xcpretty -N --no-ri --no-rdoc

script:
- rvm get head
- set -o pipefail
- xcodebuild clean build test -project LicensesViewController.xcodeproj -scheme LicensesViewController -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | xcpretty
